export const MESSAGE = {
    PROVIDE_EMAIL: 'Please provide email address.',
    PROVIDE_VALID_EMAIL: 'Please provide valid email address.',
    PROVIDE_PASSWORD: 'Please provide password.',
    PROVIDE_FIRSTNAME: 'Please provide first name.',
    FIRSTNAME_MINLENGTH: 'First name must be minimum 3 characters long.',
    FIRSTNAME_MAXLENGTH: 'First name must be maximum 15 characters long.',
    PROVIDE_LASTNAME: 'Please provide last name.',
    LASTNAME_MINLENGTH: 'Last name must be minimum 3 characters long.',
    LASTNAME_MAXLENGTH: 'Last name must be maximum 15 characters long.',
    PROVIDE_GENDER: 'Please select gender.',
    EMAIL_SENT: 'Check your email for verification!',
    PROVIDE_PHOTO: 'Please provide at least one profile image.',
    PROVIDE_ALIAS: 'Please provide alias.',
    ALIAS_MINLENGTH: 'Alias must be minimum 3 characters long.',
    ALIAS_MAXLENGTH: 'Alias must be maximum 20 characters long.',
    PROVIDE_AGE: 'Please provide age.',
    PROVIDE_ZODIAC: 'Please provide zodiac sign.',
    PROVIDE_HIEGHT: 'Please provide height.',
    PROVIDE_BODYTYPE: 'Please provide body type.',
    PROVIDE_WORK_SCHOOL: 'Please provide your current title.',
    WORK_SCHOOL_MINLENGTH: 'Current title must be minimum 3 characters long.',
    WORK_SCHOOL_MAXLENGTH: 'Current title must be maximum 40 characters long.',
    PROVIDE_LOCATION: 'Please provide location.',
    PROVIDE_ABOUT_ME: 'Please provide about me.',
    ABOUT_ME_MINLENGTH: 'About me must be minimum 50 characters long.',
    ABOUT_ME_MAXLENGTH: 'About me must be maximum 300 characters long.',
    PROVIDE_FULLNAME: 'Please provide full name.',
    FULLNAME_MINLENGTH: 'Full name must be minimum 7 characters long.',
    FULLNAME_MAXLENGTH: 'Full name must be maximum 25 characters long.',
    PROVIDE_PHONENO: 'Please provide phone number.',
    PROVIDE_VALID_PHONENO: 'Please provide valid phone number.',
    PHONENO_MINLENGTH: 'Phone number must be minimum 10 digit long.',
    PHONENO_ALREADY_IN_USE: 'This phone number is already in use.',
    PROVIDE_OLD_PASSWORD_FOR_EMAIL: 'Please provide old password for change email address.',
    PASSWORD_MIN_LENGTH: 'Password must at list 6 characters long.',
    PASSWORD_DOES_NOT_MATCH: 'New password and confirm password does not match.',
    PROVIDE_OLD_PASSWORD_FOR_PASSWORD: 'Please provide old password for change password.',
    EMAIL_IN_USE: 'This email address is already in use.',
    PROVIDE_SUBJECT: 'Please provide subject.',
    SUBJECT_MINLENGTH: 'Subject must be minimum 10 characters long.',
    SUBJECT_MAXLENGTH: 'Subject must be maximum 30 characters long.',
    PROVIDE_DESCRIPTION: 'Please provide problem description.',
    DESCRIPTION_MINLENGTH: 'Problem description must be minimum 50 characters long.',
    DESCRIPTION_MAXLENGTH: 'Problem description must be maximum 300 characters long.',
    REPORT_SUCCESS: 'Problem has been reported successfully. Xclusive team will get back to you further on it.',
    NETWORK_ERROR: 'Sorry we are unable to connect with the server, please try again later',
    PROVIDE_PREFERRED_DATE: 'Please select at least 1 preferred date.',
    PROVIDE_DINNER_RATE: 'Please provide your dinner rate',
    PROVIDE_COCKTAIL_RATE: 'Please provide your cocktails rate',
    PROVIDE_EVENT_RATE: 'Please provide your special event rate',
    PROVIDE_VIDEO_CHAT_RATE: 'Please provide your video chat rate',
    DATES_LIMIT_ERROR: 'Please select at most 3 preferred date.',
    FBACCOUNT_ALREADY_IN_USE: 'This facebook account is already in use.',
    GOOGLEACCOUNT_ALREADY_IN_USE: 'This google account is already in use.',
    AGE_RESTRICTION: 'Only user with age 21 or above can use this application.',
    PROVIDE_DOB: 'Please provide date of birth.',
    PROVIDE_SSN_LAST_FOUR: 'Please provide ssn last 4.',
    PROVIDE_INDUSTRY: 'Please provide industry.',
    PROVIDE_BUSINESS_WEBSITE: 'Please provide business website.',
    PROVIDE_ADDRESS_LINE1: 'Please provide address line 1.',
    PROVIDE_CITY: 'Please provide city.',
    PROVIDE_STATE: 'Please provide state.',
    PROVIDE_POSTAL_CODE: 'Please provide postal or zip code.',
    SSN_LAST_FOUR_LENGTH: 'SSN last 4 must be 4 digits long.',
    PROVIDE_POSTAL_CODE_LENGTH: 'Postal code must be 4 to 6 digits long.',
    PROVIDE_VALID_SSN_LAST_FOUR: 'Please provide valid SSN last 4.',
    PROVIDE_VALID_POSTAL_CODE: 'Please provide valid postal or zip code.'
}
